export interface ApplicantData {
    id: string;
    candidate_id: string;
    candidate_name: string;
    phone: string;
    email: string;
    current_organization: string;
    payroll_organisation: string;
    total_experience: string;
    relevant_experience: string;
    pan_number: string;
    current_location: string;
    preffered_location: string;
    skill_sets: string;
    notice_period: string;
    current_ctc: string;
    expected_ctc: string;
    resume: string;
    created_by: string;
    created: string;
    last_updated_by_user: string;
    last_updated_by_candidate: string;
    status: 'active' | 'inactive';
}

export const mockApplicantsData: ApplicantData[] = [
    {
        id: '1',
        candidate_id: 'APP001',
        candidate_name: 'John Doe',
        phone: '+1-555-0101',
        email: 'john.doe@email.com',
        current_organization: 'TechCorp Inc.',
        payroll_organisation: 'TechCorp Payroll Services',
        total_experience: '5.2',
        relevant_experience: '4.1',
        pan_number: 'ABCDE1234F',
        current_location: 'San Francisco, CA',
        preffered_location: 'San Francisco, CA',
        skill_sets: 'React, Node.js, TypeScript, MongoDB',
        notice_period: '30 Days',
        current_ctc: '₹12,00,000',
        expected_ctc: '₹15,00,000',
        resume: 'john_doe_resume.pdf',
        created_by: 'HR Manager - Sarah Wilson',
        created: '2024-01-15',
        last_updated_by_user: 'System Admin - Mike Johnson',
        last_updated_by_candidate: '2024-02-01',
        status: 'active',
    },
    {
        id: '2',
        candidate_id: 'APP002',
        candidate_name: 'Jane Smith',
        phone: '+1-555-0102',
        email: 'jane.smith@email.com',
        current_organization: 'DataSoft Solutions',
        payroll_organisation: 'DataSoft HR Solutions Ltd.',
        total_experience: '3.8',
        relevant_experience: '3.2',
        pan_number: 'FGHIJ5678K',
        current_location: 'New York, NY',
        preffered_location: 'Remote / New York',
        skill_sets: 'Python, Django, PostgreSQL, AWS',
        notice_period: '15 Days',
        current_ctc: '₹8,50,000',
        expected_ctc: '₹11,00,000',
        resume: 'jane_smith_resume.pdf',
        created_by: 'Recruiter - Alex Thompson',
        created: '2024-01-18',
        last_updated_by_user: 'HR Manager - Sarah Wilson',
        last_updated_by_candidate: '2024-01-25',
        status: 'active',
    },
    {
        id: '3',
        candidate_id: 'APP003',
        candidate_name: 'Mike Johnson',
        phone: '+1-555-0103',
        email: 'mike.johnson@email.com',
        current_organization: 'CloudTech Ltd.',
        payroll_organisation: 'CloudTech Global Payroll',
        total_experience: '7.5',
        relevant_experience: '6.8',
        pan_number: 'LMNOP9012Q',
        current_location: 'Austin, TX',
        preffered_location: 'Austin, TX / Dallas, TX',
        skill_sets: 'Java, Spring Boot, AWS, Kubernetes',
        notice_period: '60 Days',
        current_ctc: '₹18,00,000',
        expected_ctc: '₹22,00,000',
        resume: 'mike_johnson_resume.pdf',
        created_by: 'Team Lead - Jennifer Davis',
        created: '2024-01-12',
        last_updated_by_user: 'Recruiter - Alex Thompson',
        last_updated_by_candidate: '2024-01-30',
        status: 'inactive',
    },
    {
        id: '4',
        candidate_id: 'APP004',
        candidate_name: 'Sarah Williams',
        phone: '+1-555-0104',
        email: 'sarah.williams@email.com',
        current_organization: 'InnovateSoft',
        payroll_organisation: 'InnovateSoft Human Resources',
        total_experience: '4.3',
        relevant_experience: '3.9',
        pan_number: 'RSTUV3456W',
        current_location: 'Seattle, WA',
        preffered_location: 'Seattle, WA / Portland, OR',
        skill_sets: 'Angular, .NET Core, Azure, SQL Server',
        notice_period: 'Immediate',
        current_ctc: '₹10,50,000',
        expected_ctc: '₹13,50,000',
        resume: 'sarah_williams_resume.pdf',
        created_by: 'HR Manager - Sarah Wilson',
        created: '2024-01-20',
        last_updated_by_user: 'System Admin - Mike Johnson',
        last_updated_by_candidate: '2024-02-03',
        status: 'active',
    },
    {
        id: '5',
        candidate_id: 'APP005',
        candidate_name: 'David Brown',
        phone: '+1-555-0105',
        email: 'david.brown@email.com',
        current_organization: 'MegaCorp Systems',
        payroll_organisation: 'MegaCorp Employee Services',
        total_experience: '2.1',
        relevant_experience: '1.8',
        pan_number: 'XYZAB7890C',
        current_location: 'Denver, CO',
        preffered_location: 'Remote / Denver, CO',
        skill_sets: 'Vue.js, Laravel, MySQL, Docker',
        notice_period: '45 Days',
        current_ctc: '₹6,00,000',
        expected_ctc: '₹8,50,000',
        resume: 'david_brown_resume.pdf',
        created_by: 'Recruiter - Alex Thompson',
        created: '2024-01-25',
        last_updated_by_user: 'Team Lead - Jennifer Davis',
        last_updated_by_candidate: '2024-02-02',
        status: 'inactive',
    },
    {
        id: '6',
        candidate_id: 'APP006',
        candidate_name: 'Emily Davis',
        phone: '+1-555-0106',
        email: 'emily.davis@email.com',
        current_organization: 'StartupHub Inc.',
        payroll_organisation: 'StartupHub Payroll Management',
        total_experience: '6.7',
        relevant_experience: '5.9',
        pan_number: 'DEFGH1357I',
        current_location: 'Boston, MA',
        preffered_location: 'Boston, MA / Cambridge, MA',
        skill_sets: 'React Native, Firebase, GraphQL, Redux',
        notice_period: '30 Days',
        current_ctc: '₹14,00,000',
        expected_ctc: '₹17,50,000',
        resume: 'emily_davis_resume.pdf',
        created_by: 'HR Manager - Sarah Wilson',
        created: '2024-01-10',
        last_updated_by_user: 'Recruiter - Alex Thompson',
        last_updated_by_candidate: '2024-01-28',
        status: 'active',
    },
    {
        id: '7',
        candidate_id: 'APP007',
        candidate_name: 'Robert Wilson',
        phone: '+1-555-0107',
        email: 'robert.wilson@email.com',
        current_organization: 'Enterprise Solutions Corp',
        payroll_organisation: 'Enterprise HR & Payroll Division',
        total_experience: '9.2',
        relevant_experience: '8.5',
        pan_number: 'QWERT2468P',
        current_location: 'Chicago, IL',
        preffered_location: 'Chicago, IL / Milwaukee, WI',
        skill_sets: 'C#, .NET Framework, SQL Server, Azure DevOps',
        notice_period: '90 Days',
        current_ctc: '₹25,00,000',
        expected_ctc: '₹30,00,000',
        resume: 'robert_wilson_resume.pdf',
        created_by: 'Team Lead - Jennifer Davis',
        created: '2024-01-05',
        last_updated_by_user: 'HR Manager - Sarah Wilson',
        last_updated_by_candidate: '2024-01-22',
        status: 'active',
    },
    {
        id: '8',
        candidate_id: 'APP008',
        candidate_name: 'Lisa Anderson',
        phone: '+1-555-0108',
        email: 'lisa.anderson@email.com',
        current_organization: 'Digital Dynamics Ltd.',
        payroll_organisation: 'Digital Dynamics Workforce Solutions',
        total_experience: '1.5',
        relevant_experience: '1.2',
        pan_number: 'UIOPL3579A',
        current_location: 'Phoenix, AZ',
        preffered_location: 'Phoenix, AZ / Tucson, AZ',
        skill_sets: 'HTML, CSS, JavaScript, Bootstrap',
        notice_period: '15 Days',
        current_ctc: '₹4,50,000',
        expected_ctc: '₹6,00,000',
        resume: 'lisa_anderson_resume.pdf',
        created_by: 'Recruiter - Alex Thompson',
        created: '2024-01-28',
        last_updated_by_user: 'System Admin - Mike Johnson',
        last_updated_by_candidate: '2024-02-05',
        status: 'inactive',
    },
    {
        id: '9',
        candidate_id: 'APP009',
        candidate_name: 'Kevin Martinez',
        phone: '+1-555-0109',
        email: 'kevin.martinez@email.com',
        current_organization: 'Global Tech Innovations',
        payroll_organisation: 'Global Tech HR Services',
        total_experience: '12.3',
        relevant_experience: '11.8',
        pan_number: 'ASDFG4680B',
        current_location: 'Los Angeles, CA',
        preffered_location: 'Los Angeles, CA / San Diego, CA',
        skill_sets: 'Python, Machine Learning, TensorFlow, AWS',
        notice_period: '60 Days',
        current_ctc: '₹35,00,000',
        expected_ctc: '₹42,00,000',
        resume: 'kevin_martinez_resume.pdf',
        created_by: 'HR Manager - Sarah Wilson',
        created: '2024-01-08',
        last_updated_by_user: 'Team Lead - Jennifer Davis',
        last_updated_by_candidate: '2024-01-20',
        status: 'active',
    },
    {
        id: '10',
        candidate_id: 'APP010',
        candidate_name: 'Amanda Taylor',
        phone: '+1-555-0110',
        email: 'amanda.taylor@email.com',
        current_organization: 'NextGen Software Solutions',
        payroll_organisation: 'NextGen Employee Management',
        total_experience: '8.7',
        relevant_experience: '7.9',
        pan_number: 'ZXCVB1357M',
        current_location: 'Miami, FL',
        preffered_location: 'Miami, FL / Orlando, FL',
        skill_sets: 'Ruby on Rails, PostgreSQL, Redis, Heroku',
        notice_period: '45 Days',
        current_ctc: '₹20,00,000',
        expected_ctc: '₹24,00,000',
        resume: 'amanda_taylor_resume.pdf',
        created_by: 'Recruiter - Alex Thompson',
        created: '2024-01-14',
        last_updated_by_user: 'HR Manager - Sarah Wilson',
        last_updated_by_candidate: '2024-01-31',
        status: 'inactive',
    },
];