import React, {
  useState,
  useEffect,
  useCallback,
  useImperativeHandle,
  forwardRef,
} from 'react';
import { ApplicantHeaderFormData } from '../../../../utils/api/CandidatesAPI';
import EnhancedInputField from '../../../molecules/EnhancedInputField';
import AsyncSelect from '../../../atoms/AsyncSelect';
import CountryStateCity from '../../../molecules/CountryStateCity';
import AvatarUpload from '../../../molecules/AvatarUpload';
import ContactFieldWithValidation from '../../../molecules/ContactFieldWithValidation/ContactFieldWithValidation'; // Corrected import path
import Icon from '../../../atoms/Icon';
import { getDesignationOptionFromValue } from '../helper';
import { ValidationPatterns } from '../../../molecules/CommonFormFields/CommonFormFields';
import FileUploadService from '../../../../services/fileUploadService';
import Dropdown from '../../../atoms/Dropdown';
import { useStaticDropdowns } from '../../../../hooks/useDropdowns';
import { parseResume } from '../../../../utils/resumeParser';
import { showSuccessToast, showErrorToast } from '../../../../utils/toast';

interface HeaderFormProps {
  initialData: ApplicantHeaderFormData;
  onDataChange: (data: any) => void;
  designationAsyncOptions: any[];
  designationLoading: boolean;
  applicantData: any;
  onValidationChange?: (isValid: boolean) => void;
  onUploadStateChange?: (uploading: boolean) => void; // Callback to disable save button
  searchDesignations?: (term: string) => void; // Search function for designations
}

export const HeaderForm = forwardRef<any, HeaderFormProps>(
  (
    {
      initialData,
      onDataChange,
      designationAsyncOptions,
      designationLoading,
      applicantData,
      onValidationChange,
      onUploadStateChange,
      searchDesignations,
    },
    ref
  ) => {
    const [data, setData] = useState(
      initialData || {
        first_name: '',
        middle_name: '',
        last_name: '',
        display_name: '',
        candidate_id: '',
        phone: '',
        email: '',
        alternative_phone: '',
        alternative_email: '',
        current_address: '',
        country: '',
        state: '',
        city: '',
        designation: '',
        current_city: '',
        date_of_birth: '',
        linkedin_profile: '',
        pan_number: '',
        uan_number: '',
        profile_picture: null,
        profile_picture_removed: false,
        profile_picture_url: null,
        resume: null,
        resume_url: null,
        is_actively_looking: false,
        flag: 'Blue', // Default to Blue
      }
    );

    // Fetch static dropdowns for flags
    const { flagsOptions, loading: flagsLoading } = useStaticDropdowns();

    const [lastSentData, setLastSentData] = useState(data);
    const [focusedField, setFocusedField] = useState<string | null>(null);
    const [validationErrors, setValidationErrors] = useState<
      Record<string, string>
    >({});

    // Upload states
    const [uploadStates, setUploadStates] = useState({
      avatar: { uploading: false, error: null as string | null },
      resume: { uploading: false, error: null as string | null },
    });

    const [photoViewUrl, setPhotoViewUrl] = useState<string | undefined>(undefined);

    // Fetch secure photo URL for existing picture
    useEffect(() => {
      const fetchPhotoUrl = async () => {
        // Only fetch if handled by applicantData and not already manually uploaded/removed
        if (applicantData?.candidate_picture && !data.profile_picture && !data.profile_picture_removed) {
          try {
            const secureUrl = await FileUploadService.getFileViewUrl(applicantData.candidate_picture);
            setPhotoViewUrl(secureUrl);
          } catch (error) {
            console.error('Error fetching secure photo URL:', error);
            setPhotoViewUrl(undefined);
          }
        } else if (!applicantData?.candidate_picture || data.profile_picture_removed) {
          setPhotoViewUrl(undefined);
        }
      };

      fetchPhotoUrl();
    }, [applicantData?.candidate_picture, data.profile_picture, data.profile_picture_removed]);

    useEffect(() => {
      if (initialData) {
        const dataWithDefaultFlag = {
          ...initialData,
          flag: initialData.flag || 'Blue',
        };
        setData(dataWithDefaultFlag);
        setLastSentData(dataWithDefaultFlag);
      }
    }, [initialData]);

    // Compute auto-generated display name using useMemo to avoid re-renders
    const autoGeneratedDisplayName = React.useMemo(() => {
      return [data.first_name, data.middle_name, data.last_name]
        .filter(Boolean)
        .join(' ');
    }, [data.first_name, data.middle_name, data.last_name]);

    // Update display_name only when name fields change and user is not actively typing
    // This prevents flickering during typing
    React.useEffect(() => {
      // Use a small timeout to debounce the update
      const timeoutId = setTimeout(() => {
        if (data.display_name !== autoGeneratedDisplayName) {
          setData(prev => ({ ...prev, display_name: autoGeneratedDisplayName }));
        }
      }, 100); // 100ms debounce

      return () => clearTimeout(timeoutId);
    }, [autoGeneratedDisplayName]); // Only depend on autoGeneratedDisplayName, not data.display_name





    // Send updates when data changes, but debounce to prevent excessive re-renders
    useEffect(() => {
      // Debounce the data change notification to prevent screen flickering
      const timeoutId = setTimeout(() => {
        if (JSON.stringify(data) !== JSON.stringify(lastSentData)) {
          onDataChange(data);
          setLastSentData(data);
        }
      }, 300); // 300ms debounce for smoother experience

      return () => clearTimeout(timeoutId);
    }, [data, onDataChange]);

    // Trigger validation when errors change
    useEffect(() => {
      const isValid = Object.keys(validationErrors).length === 0;
      onValidationChange?.(isValid);
    }, [validationErrors, onValidationChange]);

    // Notify parent of upload state changes
    useEffect(() => {
      const isAnyUploading =
        uploadStates.avatar.uploading || uploadStates.resume.uploading;
      onUploadStateChange?.(isAnyUploading);
    }, [uploadStates, onUploadStateChange]);

    // Validation functions
    const validateField = useCallback((field: string, value: string) => {
      let error = '';

      switch (field) {
        case 'first_name':
          if (!value.trim()) error = 'First name is required';
          break;
        case 'last_name':
          if (!value.trim()) error = 'Last name is required';
          break;
        case 'email':
          if (!value.trim()) {
            error = 'Email is required';
          } else {
            error = ValidationPatterns.email(value) || '';
          }
          break;
        case 'phone':
          if (!value.trim()) {
            error = 'Phone number is required';
          } else if (!/^[0-9]{10}$/.test(value)) {
            error = 'Phone number must be exactly 10 digits';
          }
          break;
        case 'pan_number':
          if (!value.trim()) {
            error = 'PAN number is required';
          } else {
            error = ValidationPatterns.pan(value) || '';
          }
          break;
        case 'date_of_birth':
          if (!value.trim()) {
            error = 'Date of birth is required';
          } else {
            error = ValidationPatterns.dateOfBirth(value) || '';
          }
          break;
        case 'designation':
          if (!value.trim()) {
            error = 'Designation is required';
          }
          break;
        // Current Address fields are now optional - no validation
      }

      return error;
    }, []);

    // Immediate avatar upload handler (like Add Candidate)
    const handleAvatarUpload = useCallback(
      async (file: File | null) => {
        if (!file) {
          // Clear everything when file is explicitly removed
          const newData = {
            ...data,
            profile_picture: null,
            profile_picture_url: null,
            profile_picture_removed: true,
          };
          setData(newData);
          onDataChange(newData);
          setLastSentData(newData);
          setUploadStates(prev => ({
            ...prev,
            avatar: { uploading: false, error: null },
          }));
          return;
        }

        // Set uploading state
        setUploadStates(prev => ({
          ...prev,
          avatar: { uploading: true, error: null },
        }));

        try {
          // Validate file
          const validation = FileUploadService.validateFile(file, {
            maxSize: 5,
            allowedTypes: [
              'image/jpeg',
              'image/png',
              'image/gif',
              'image/webp',
            ],
          });

          if (!validation.valid) {
            throw new Error(validation.error || 'Invalid image file');
          }

          // Upload to server immediately
          const uploadResponse =
            await FileUploadService.uploadCandidateAvatar(file);
          console.log('Avatar uploaded successfully:', uploadResponse);

          // Update form with uploaded URL
          const newData = {
            ...data,
            profile_picture: file,
            profile_picture_url: uploadResponse.file_url,
            profile_picture_removed: false,
          };
          setData(newData);
          onDataChange(newData);
          setLastSentData(newData);

          // Clear uploading state
          setUploadStates(prev => ({
            ...prev,
            avatar: { uploading: false, error: null },
          }));

          console.log(
            'Avatar upload completed, URL stored:',
            uploadResponse.file_url
          );
        } catch (error) {
          console.error('Avatar upload failed:', error);
          const errorMsg =
            error instanceof Error ? error.message : 'Upload failed';

          setUploadStates(prev => ({
            ...prev,
            avatar: { uploading: false, error: errorMsg },
          }));

          // Clear form data on error
          const newData = {
            ...data,
            profile_picture: null,
            profile_picture_url: null,
            profile_picture_removed: false,
          };
          setData(newData);
          onDataChange(newData);
          setLastSentData(newData);
        }
      },
      [data, onDataChange]
    );

    // Immediate resume upload handler (like Add Candidate)
    const handleResumeUpload = useCallback(
      async (file: File | null) => {
        if (!file) {
          // Clear everything when file is explicitly removed
          const newData = {
            ...data,
            resume: null,
            resume_url: null,
          };
          setData(newData);
          onDataChange(newData);
          setLastSentData(newData);
          setUploadStates(prev => ({
            ...prev,
            resume: { uploading: false, error: null },
          }));
          // Show validation error for required field
          setValidationErrors(prev => ({
            ...prev,
            resume: 'Resume is required',
          }));
          return;
        }

        // Set uploading state
        setUploadStates(prev => ({
          ...prev,
          resume: { uploading: true, error: null },
        }));

        try {
          // Validate file
          const validation = FileUploadService.validateFile(file, {
            maxSize: 10,
            allowedTypes: [
              'application/pdf',
              'application/msword',
              'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            ],
          });

          if (!validation.valid) {
            throw new Error(validation.error || 'Invalid resume file');
          }

          // Upload to server immediately
          const uploadResponse = await FileUploadService.uploadResume(file);
          console.log('Resume uploaded successfully:', uploadResponse);

          // Parse the resume with textCV only
          let textCV = '';
          try {
            const parsedData = await parseResume(file);
            if (parsedData?.textCV) {
              textCV = parsedData.textCV;
              console.log('TextCV extracted successfully, length:', textCV.length);
            }
          } catch (parseError) {
            console.warn('Failed to extract textCV from resume:', parseError);
            // Continue even if parsing fails - textCV extraction is optional
          }

          // Update form with uploaded URL and textCV
          const newData = {
            ...data,
            resume: file,
            resume_url: uploadResponse.file_url,
            text_cv: textCV, // Store extracted textCV
          };
          setData(newData);
          onDataChange(newData);
          setLastSentData(newData);

          // Clear uploading state
          setUploadStates(prev => ({
            ...prev,
            resume: { uploading: false, error: null },
          }));

          showSuccessToast('Resume uploaded and parsed successfully!');
          console.log(
            'Resume upload completed, URL stored:',
            uploadResponse.file_url
          );

          // Clear validation error
          setValidationErrors(prev => ({ ...prev, resume: '' }));
        } catch (error) {
          console.error('Resume upload failed:', error);
          const errorMsg =
            error instanceof Error ? error.message : 'Upload failed';

          setUploadStates(prev => ({
            ...prev,
            resume: { uploading: false, error: errorMsg },
          }));

          // Clear form data on error
          const newData = {
            ...data,
            resume: null,
            resume_url: null,
          };
          setData(newData);
          onDataChange(newData);
          setLastSentData(newData);
          setValidationErrors(prev => ({
            ...prev,
            resume: 'Resume is required',
          }));

          showErrorToast(`Resume upload failed: ${errorMsg}`);
        }
      },
      [data, onDataChange]
    );

    // Handler for removing resume (trash icon)
    const handleRemoveResume = useCallback(() => {
      const newData = {
        ...data,
        resume: null,
        resume_url: null,
      };
      setData(newData);
      onDataChange(newData);
      setLastSentData(newData);
      setUploadStates(prev => ({
        ...prev,
        resume: { uploading: false, error: null },
      }));
      setValidationErrors(prev => ({ ...prev, resume: 'Resume is required' }));
    }, [data, onDataChange]);

    // Handler for avatar validation errors (file size, etc.)
    const handleAvatarValidationError = useCallback((error: string) => {
      setUploadStates(prev => ({
        ...prev,
        avatar: { uploading: false, error },
      }));
    }, []);

    const handleChange = useCallback(
      (
        field: keyof ApplicantHeaderFormData | 'flag',
        value: string | File | null | boolean
      ) => {
        if (field === 'profile_picture' && value instanceof File) {
          // Only call upload handler for actual File objects (user selections)
          handleAvatarUpload(value);
        } else if (field === 'resume' && value instanceof File) {
          // Only call upload handler for actual File objects (user selections)
          handleResumeUpload(value);
        } else {
          // Special handling for phone: only allow digits, max 10
          if (field === 'phone' && typeof value === 'string') {
            let digitsOnly = value.replace(/\D/g, '');
            if (digitsOnly.length > 10) digitsOnly = digitsOnly.slice(0, 10);
            setData(prev => ({ ...prev, [field]: digitsOnly }));
            // Validation is handled by ContactFieldWithValidation component
          } else {
            // For all other cases (strings, null values, etc.), just update data
            // cascading reset logic
            let updates: any = { [field]: value };
            if (field === 'country') {
              updates.state = '';
              updates.city = '';
            } else if (field === 'state') {
              updates.city = '';
            }

            setData(prev => ({ ...prev, ...updates }));

            // Validate field on change for string values
            if (typeof value === 'string') {
              const error = validateField(field, value);
              setValidationErrors(prev => ({
                ...prev,
                [field]: error,
              }));
            }
          }
        }
      },
      [handleAvatarUpload, handleResumeUpload, validateField]
    );

    const handleFocus = useCallback((field: string) => {
      setFocusedField(field);
    }, []);

    const handleBlur = useCallback(() => {
      setFocusedField(null);
    }, []);

    // Helper function to capitalize names (first letter uppercase, rest lowercase)
    const capitalizeName = (name: string): string => {
      if (!name) return '';
      return name
        .trim()
        .split(' ')
        .map(word => {
          if (!word) return '';
          return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
        })
        .join(' ');
    };

    // --- Place validateAllFields and useImperativeHandle after all hooks and before return ---
    const validateAllFields = useCallback(() => {
      const requiredFields = [
        'first_name',
        'last_name',
        'email',
        'phone',
        'pan_number',
        'date_of_birth',
        'designation',
        // Current Address fields are now optional
      ];
      let errors: Record<string, string> = {};
      requiredFields.forEach(field => {
        const value = (data as any)[field] || '';
        let error = validateField(field, value);

        // Preserve async duplicate errors if static validation passes
        if (!error && (field === 'phone' || field === 'email') && validationErrors[field]) {
          error = validationErrors[field];
        }



        if (error) errors[field] = error;
      });

      // Check LinkedIn validation
      if (data.linkedin_profile) {
        const linkedinRegex = /^https?:\/\/(www\.)?linkedin\.com\/.*$/;
        if (!linkedinRegex.test(data.linkedin_profile)) {
          errors.linkedin_profile = 'Please enter a valid LinkedIn profile URL';
        }
      }

      // Optional field validations - only validate if field has value
      if (data.alternative_phone?.trim()) {
        if (!/^[0-9]{10}$/.test(data.alternative_phone)) {
          errors.alternative_phone = 'Alternative phone must be exactly 10 digits';
        }
      }

      if (data.alternative_email?.trim()) {
        const emailError = ValidationPatterns.email(data.alternative_email);
        if (emailError) {
          errors.alternative_email = emailError;
        }
      }

      // Resume required check
      // if (!data.resume && !data.resume_url) {
      //     errors.resume = 'Resume is required';
      // }
      setValidationErrors(errors);
      onValidationChange?.(Object.keys(errors).length === 0);
      return Object.keys(errors).length === 0;
    }, [data, validateField, onValidationChange, validationErrors]);

    useImperativeHandle(ref, () => ({
      validateAllFields,
    }));

    return (
      <div
        className="p-6 space-y-6"
        onFocus={e =>
          handleFocus(e.target.getAttribute('data-field') || 'unknown')
        }
        onBlur={handleBlur}
      >
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <EnhancedInputField
            label="First Name"
            value={data.first_name}
            onChange={value => handleChange('first_name', capitalizeName(value))}
            required
            error={validationErrors.first_name}
          />
          <EnhancedInputField
            label="Middle Name"
            value={data.middle_name}
            onChange={value => handleChange('middle_name', capitalizeName(value))}
          />
          <EnhancedInputField
            label="Last Name"
            value={data.last_name}
            onChange={value => handleChange('last_name', capitalizeName(value))}
            required
            error={validationErrors.last_name}
          />
          <EnhancedInputField
            label="Display Name"
            value={data.display_name}
            onChange={value => handleChange('display_name', value)}
            required
            helpText="Auto-generated from name fields"
            disabled
          />
          <EnhancedInputField
            label="Candidate ID"
            value={data.candidate_id}
            onChange={value => handleChange('candidate_id', value)}
            required
            helpText="System allocated candidate ID"
            disabled
          />
          <ContactFieldWithValidation
            value={data.phone || ''}
            type="phone"
            onChange={(value: string) => handleChange('phone', value)}
            excludeId={applicantData.candidate_id || applicantData.id || applicantData._id}
            onValidationChange={(isValid: boolean, error?: string) => {
              setValidationErrors(prev => {
                const newErrors = { ...prev };
                if (!isValid && error) {
                  newErrors.phone = error;
                } else {
                  delete newErrors.phone;
                }
                return newErrors;
              });
            }}
          />
          <ContactFieldWithValidation
            value={data.email || ''}
            type="email"
            onChange={(value: string) => handleChange('email', value)}
            excludeId={applicantData.candidate_id || applicantData.id || applicantData._id}
            onValidationChange={(isValid: boolean, error?: string) => {
              setValidationErrors(prev => {
                const newErrors = { ...prev };
                if (!isValid && error) {
                  newErrors.email = error;
                } else {
                  delete newErrors.email;
                }
                return newErrors;
              });
            }}
          />
          <EnhancedInputField
            label="Alternative Phone"
            value={data.alternative_phone}
            onChange={value => {
              let digitsOnly = value.replace(/\D/g, '');
              if (digitsOnly.length > 10) digitsOnly = digitsOnly.slice(0, 10);
              handleChange('alternative_phone', digitsOnly);
              // Validate on change
              if (digitsOnly.trim()) {
                let error = '';
                if (!/^[0-9]{10}$/.test(digitsOnly)) {
                  error = 'Alternative phone must be exactly 10 digits';
                }
                setValidationErrors(prev => ({
                  ...prev,
                  alternative_phone: error,
                }));
              } else {
                // Optional field - clear error if empty
                setValidationErrors(prev => {
                  const newErrors = { ...prev };
                  delete newErrors.alternative_phone;
                  return newErrors;
                });
              }
            }}
            placeholder="Enter alternative phone number (10 digits)"
            error={validationErrors.alternative_phone}
          />
          <EnhancedInputField
            label="Alternative Email"
            value={data.alternative_email}
            onChange={value => {
              handleChange('alternative_email', value);
              // Validate on change
              if (value.trim()) {
                const error = ValidationPatterns.email(value) || '';
                setValidationErrors(prev => ({
                  ...prev,
                  alternative_email: error,
                }));
              } else {
                // Optional field - clear error if empty
                setValidationErrors(prev => {
                  const newErrors = { ...prev };
                  delete newErrors.alternative_email;
                  return newErrors;
                });
              }
            }}
            placeholder="Enter alternative email address"
            type="email"
            error={validationErrors.alternative_email}
          />
          <AsyncSelect
            label="Designation"
            value={getDesignationOptionFromValue(
              data.designation,
              designationAsyncOptions
            )}
            onChange={option => {
              // Store by 'name' (label) as per user preference
              handleChange('designation', option?.label || '');
              // Immediately update for dropdown selections
              setFocusedField(null);
            }}
            required
            onInputChange={(inputValue: string) => {
              // Handle search input - call the search function from props
              if (searchDesignations && typeof inputValue === 'string') {
                searchDesignations(inputValue);
              }
            }}
            options={designationAsyncOptions}
            placeholder="Select designation"
            isLoading={designationLoading}
            showAddButton={true}
            dropdownType="Designation"
            dropdownLabel="Designation"
            onOptionAdded={newOption => {
              // Refresh designation options if needed
              if (searchDesignations) {
                searchDesignations('');
              }
            }}
            error={validationErrors.designation}
          />
          <EnhancedInputField
            label="Date of Birth"
            type="date"
            value={data.date_of_birth}
            onChange={value => handleChange('date_of_birth', value)}
            required
            error={validationErrors.date_of_birth}
          />
          <EnhancedInputField
            label="LinkedIn Profile"
            value={data.linkedin_profile}
            onChange={value => handleChange('linkedin_profile', value)}
            placeholder="https://www.linkedin.com/in/username"
            type="url"
            textTransform="none"
            error={validationErrors.linkedin_profile}
            validate={val => {
              if (!val) return null;
              const linkedinRegex = /^https?:\/\/(www\.)?linkedin\.com\/.*$/;
              return linkedinRegex.test(val)
                ? null
                : 'Please enter a valid LinkedIn profile URL';
            }}
          />
          <EnhancedInputField
            label="PAN Number"
            value={data.pan_number}
            onChange={value => handleChange('pan_number', value)}
            required
            error={validationErrors.pan_number}
            disabled={!!applicantData.pan_number}
          />
          <EnhancedInputField
            label="UAN Number"
            value={data.uan_number}
            onChange={value => handleChange('uan_number', value)}
          />
        </div>

        {/* Location Section */}
        <div className="space-y-4">
          {/* {(data.country || data.state || data.city) && (
            <div className="flex items-center space-x-2 p-2 bg-blue-50 border-l-4 border-blue-400 rounded">
              <Icon name="map-pin" className="h-4 w-4 text-blue-600" />
              <span className="text-sm text-blue-800">
                {[data.country, data.state, data.city]
                  .filter(Boolean)
                  .join(', ')}
              </span>
            </div>
          )} */}

          <EnhancedInputField
            label="Current Address"
            value={data.current_address}
            onChange={value => handleChange('current_address', value)}
            placeholder="Enter your current residential address"
            textTransform="none"
            required={false}
            error={validationErrors.current_address}
          />

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <CountryStateCity
              type="country"
              label="Country"
              value={data.country}
              onChange={value => handleChange('country', value)}
              placeholder="Select country..."
              required={false}
              error={validationErrors.country}
            />
            <CountryStateCity
              type="state"
              label="State"
              value={data.state}
              onChange={value => handleChange('state', value)}
              country={data.country}
              placeholder="Select state..."
              required={false}
              error={validationErrors.state}
            />
            <CountryStateCity
              type="city"
              label="City"
              value={data.city}
              onChange={value => handleChange('city', value)}
              country={data.country}
              state={data.state}
              placeholder="Select city..."
              required={false}
              error={validationErrors.city}
            />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <AvatarUpload
            label="Profile Picture"
            preview={
              data.profile_picture_removed
                ? undefined
                : data.profile_picture
                  ? URL.createObjectURL(data.profile_picture)
                  : photoViewUrl || applicantData.candidate_picture
            }
            value={data.profile_picture}
            onChange={file => handleChange('profile_picture', file)}
            onValidationError={handleAvatarValidationError}
            size="lg"
            accept=".jpg,.jpeg,.png,.gif"
            maxSize={5}
            required
            showFileName={true}
            uploading={uploadStates.avatar.uploading}
            uploadError={uploadStates.avatar.error || undefined}
          />

          {/* Combined Resume Section */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-gray-900">
              Resume <span className="text-red-600">*</span>
            </label>

            <div className="border border-gray-300 rounded-lg p-4 bg-white space-y-3">
              {/* Current Resume View Section */}
              {applicantData.resume_url && (
                <div className="flex items-center justify-between p-3 bg-blue-50 border border-blue-200 rounded-md">
                  <div className="flex items-center gap-2">
                    <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                      <path d="M8 16.5a1 1 0 11-2 0 1 1 0 012 0zM15 7a1 1 0 11-2 0 1 1 0 012 0z" />
                      <path d="M12.5 1a.5.5 0 00-.5.5v12a.5.5 0 001 0V1.5a.5.5 0 00-.5-.5zM9 4a.5.5 0 00-.5.5v9a.5.5 0 001 0V4.5A.5.5 0 009 4zM5.5 7a.5.5 0 00-.5.5v6a.5.5 0 001 0v-6a.5.5 0 00-.5-.5z" />
                    </svg>
                    <span className="text-sm text-gray-700 font-medium">Current Resume on File</span>
                  </div>
                  <button
                    type="button"
                    onClick={() => FileUploadService.openFile(applicantData.resume_url, 'view')}
                    className="px-3 py-1.5 text-xs font-medium text-blue-600 hover:text-blue-800 hover:bg-blue-100 rounded transition-colors"
                  >
                    View
                  </button>
                </div>
              )}

              {/* Upload/Replace Resume Section */}
              <div>
                <label className="block text-xs font-medium text-gray-600 mb-2">
                  {applicantData.resume_url ? "Replace Resume" : "Upload Resume"}
                </label>
                <div className="flex items-end gap-2">
                  <div className="flex-1">
                    <label className="relative inline-flex items-center w-full">
                      <input
                        type="file"
                        accept=".pdf,.doc,.docx"
                        onChange={e => {
                          const file = e.target.files?.[0] || null;
                          handleChange('resume', file);
                        }}
                        disabled={uploadStates.resume.uploading}
                        className="hidden"
                      />
                      <span
                        className={`w-full px-4 py-2 border rounded-md text-sm font-medium cursor-pointer transition-colors flex items-center justify-center ${uploadStates.resume.uploading
                          ? 'bg-gray-100 border-gray-300 text-gray-400 cursor-not-allowed'
                          : 'bg-white border-gray-300 text-gray-700 hover:bg-gray-50 hover:border-gray-400'
                          }`}
                      >
                        {uploadStates.resume.uploading ? (
                          <>
                            <svg
                              className="animate-spin -ml-1 mr-2 h-4 w-4 text-gray-500"
                              fill="none"
                              viewBox="0 0 24 24"
                            >
                              <circle
                                className="opacity-25"
                                cx="12"
                                cy="12"
                                r="10"
                                stroke="currentColor"
                                strokeWidth="4"
                              ></circle>
                              <path
                                className="opacity-75"
                                fill="currentColor"
                                d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                              ></path>
                            </svg>
                            Processing...
                          </>
                        ) : (
                          <>
                            <svg
                              className="w-4 h-4 mr-2"
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                              />
                            </svg>
                            Choose File
                          </>
                        )}
                      </span>
                    </label>
                  </div>

                  {/* Remove Resume Button */}
                  {(data.resume || data.resume_url) && (
                    <button
                      type="button"
                      onClick={handleRemoveResume}
                      title="Remove Resume"
                      className="p-2 text-red-500 hover:text-red-700 hover:bg-red-50 rounded transition-colors border border-red-200"
                    >
                      <Icon name="trash" className="h-5 w-5" />
                    </button>
                  )}
                </div>
              </div>

              {/* File Info and Status */}
              <div className="space-y-2">
                {/* Selected File Display */}
                {data.resume && (
                  <div className="flex items-center gap-2 p-2 bg-gray-50 rounded border border-gray-200">
                    <svg className="w-4 h-4 text-gray-500" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M8 16.5a1 1 0 11-2 0 1 1 0 012 0zM15 7a1 1 0 11-2 0 1 1 0 012 0z" clipRule="evenodd" />
                    </svg>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs font-medium text-gray-700 truncate">{data.resume.name}</p>
                      <p className="text-xs text-gray-500">{(data.resume.size / 1024 / 1024).toFixed(2)} MB</p>
                    </div>
                  </div>
                )}

                {/* Help Text */}
                <p className="text-xs text-gray-500">PDF or DOCX, max 10MB</p>

                {/* Upload Error */}
                {uploadStates.resume.error && (
                  <div className="text-xs text-red-600 flex items-center gap-1">
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                    </svg>
                    {uploadStates.resume.error}
                  </div>
                )}

                {/* Validation Error */}
                {validationErrors.resume && (
                  <div className="text-xs text-red-600 flex items-center gap-1 mt-1">
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                    </svg>
                    {validationErrors.resume}
                  </div>
                )}

                {/* Upload Status Indicator */}
                {data.resume_url && !uploadStates.resume.uploading && (
                  <div className="flex items-center gap-2 text-xs text-green-600">
                    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    <span>Resume ready</span>
                  </div>
                )}
              </div>
            </div>
          </div>

        </div>

        {/* Job Search Status and Flag Section */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-900">
              Job Search Status
            </label>
            <div className="flex items-center h-10 pt-2">
              <input
                type="checkbox"
                id="actively-looking"
                checked={data.is_actively_looking}
                onChange={e =>
                  handleChange('is_actively_looking', e.target.checked)
                }
                className="h-4 w-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
              />
              <label
                htmlFor="actively-looking"
                className="text-sm ml-2 text-gray-700"
              >
                Is Actively Looking ?
              </label>
            </div>
            <p className="text-xs text-gray-500 mt-1">
              Check this if the candidate is actively seeking new job
              opportunities
            </p>
          </div>

          {/* Flag Dropdown */}
          <div className="space-y-2">
            <label className="text-sm font-medium text-gray-900">Flag</label>
            <Dropdown
              options={flagsOptions}
              value={data.flag}
              onChange={value => handleChange('flag', value)}
              placeholder="Select a flag"
              disabled={flagsLoading}
              fullWidth
            />
            {flagsLoading && (
              <p className="text-xs text-gray-500">Loading flags...</p>
            )}
          </div>
        </div>
      </div>
    );
  }
);
