/**
 * List of major Indian cities
 * Used for location validation in resume parser
 */
export const INDIAN_CITIES = [
  // Metro Cities
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Ahmedabad',
  'Chennai',
  'Kolkata',
  'Pune',

  // Tier 1 Cities
  'Surat',
  'Jaipur',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Pimpri-Chinchwad',
  'Patna',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Faridabad',
  'Meerut',
  'Rajkot',
  'Kalyan-Dombivali',
  'Vasai-Virar',
  'Varanasi',
  'Srinagar',
  'Aurangabad',
  'Dhanbad',
  'Amritsar',
  'Navi Mumbai',
  'Allahabad',
  'Ranchi',
  'Howrah',
  'Coimbatore',
  'Jabalpur',
  'Gwalior',
  'Vijayawada',
  'Jodhpur',
  'Madurai',
  'Raipur',
  'Kota',

  // Tier 2 Cities
  'Chandigarh',
  'Guwahati',
  'Thiruvananthapuram',
  'Solapur',
  'Hubli-Dharwad',
  'Tiruchirappalli',
  'Tiruppur',
  'Moradabad',
  'Mysore',
  'Bareilly',
  'Gurgaon',
  'Aligarh',
  'Jalandhar',
  'Bhubaneswar',
  'Salem',
  'Mira-Bhayandar',
  'Warangal',
  'Guntur',
  'Bhiwandi',
  'Saharanpur',
  'Gorakhpur',
  'Bikaner',
  'Amravati',
  'Noida',
  'Jamshedpur',
  'Bhilai',
  'Cuttack',
  'Firozabad',
  'Kochi',
  'Nellore',
  'Bhavnagar',
  'Dehradun',
  'Durgapur',
  'Asansol',
  'Rourkela',
  'Nanded',
  'Kolhapur',
  'Ajmer',
  'Akola',
  'Gulbarga',
  'Jamnagar',
  'Ujjain',
  'Loni',
  'Siliguri',
  'Jhansi',
  'Ulhasnagar',
  'Jammu',
  'Sangli-Miraj-Kupwad',
  'Mangalore',
  'Erode',
  'Belgaum',
  'Ambattur',
  'Tirunelveli',
  'Malegaon',
  'Gaya',
  'Jalgaon',
  'Udaipur',
  'Maheshtala',
  'Davanagere',
  'Kozhikode',
  'Kurnool',
  'Rajpur Sonarpur',
  'Rajahmundry',
  'Bokaro',
  'South Dumdum',
  'Bellary',
  'Patiala',
  'Gopalpur',
  'Agartala',
  'Bhagalpur',
  'Muzaffarnagar',
  'Bhatpara',
  'Panihati',
  'Latur',
  'Dhule',
  'Rohtak',
  'Korba',
  'Bhilwara',
  'Brahmapur',
  'Muzaffarpur',
  'Ahmednagar',
  'Mathura',
  'Kollam',
  'Avadi',
  'Kadapa',
  'Kamarhati',
  'Sambalpur',
  'Bilaspur',
  'Shahjahanpur',
  'Satara',
  'Bijapur',
  'Rampur',
  'Shivamogga',
  'Chandrapur',
  'Junagadh',
  'Thrissur',
  'Alwar',
  'Bardhaman',
  'Kulti',
  'Kakinada',
  'Nizamabad',
  'Parbhani',
  'Tumkur',
  'Khammam',
  'Ozhukarai',
  'Bihar Sharif',
  'Panipat',
  'Darbhanga',
  'Bally',
  'Aizawl',
  'Dewas',
  'Ichalkaranji',
  'Karnal',
  'Bathinda',
  'Jalna',
  'Eluru',
  'Kirari Suleman Nagar',
  'Barasat',
  'Purnia',
  'Satna',
  'Mau',
  'Sonipat',
  'Farrukhabad',
  'Sagar',
  'Rourkela',
  'Durg',
  'Imphal',
  'Ratlam',
  'Hapur',
  'Arrah',
  'Karimnagar',
  'Anantapur',
  'Etawah',
  'Ambernath',
  'North Dumdum',
  'Bharatpur',
  'Begusarai',
  'New Delhi',
  'Gandhidham',
  'Baranagar',
  'Tiruvottiyur',
  'Puducherry',
  'Sikar',
  'Thoothukudi',
  'Rewa',
  'Mirzapur',
  'Raichur',
  'Pali',
  'Raiganj',
  'Malda',
  'Unnao',
  'Jaunpur',
  'Lakhimpur',
  'Haldwani',
  'Katihar',
  'Chhapra',
  'Kadiri',
  'Ramagundam',
  'Kavali',
  'Vizianagaram',
  'Tenali',
  'Sri Ganganagar',
  'Karawal Nagar',
  'Mango',
  'Thanjavur',
  'Bulandshahr',
  'Uluberia',
  'Murwara',
  'Sambhal',
  'Singrauli',
  'Nadiad',
  'Secunderabad',
  'Naihati',
  'Yamunanagar',
  'Bidhan Nagar',
  'Pallavaram',
  'Bidar',
  'Munger',
  'Panchkula',
  'Burhanpur',
  'Raurkela Industrial Township',
  'Kharagpur',
  'Dindigul',
  'Gandhinagar',
  'Hospet',
  'Nangloi Jat',
  'Malappuram',
  'Rudrapur',
  'Hugli and Chinsurah',
  'Alappuzha',
  'Muktsar',
  'Rajpura',
  'Medinipur',
  'Habra',
  'Sasaram',
  'Hajipur',
  'Bhuj',
  'Shillong',
  'Sambalpur',
  'Shimla',
  'Nagercoil',
  'Khanna',
  'Puri',
  'Silchar',
  'Vellore',
  'Chittoor',
  'Tirupati',
  'Cuddalore',
  'Pondicherry',
  'Ratnagiri',
  'Gangtok',
  'Port Blair',
  'Dibrugarh',
  'Tezpur',
  'Jorhat',
  'Kohima',
  'Itanagar',
  'Arunachal Pradesh',
] as const;

/**
 * Validates if a location is a valid Indian city
 * @param location - Location string to validate
 * @returns true if location is a valid Indian city (case-insensitive)
 */
export const isValidIndianCity = (location: string): boolean => {
  if (!location || typeof location !== 'string') return false;

  const normalized = location.trim().toLowerCase();
  return INDIAN_CITIES.some(city => city.toLowerCase() === normalized);
};

/**
 * Capitalizes location to proper format (e.g., "hyderabad" -> "Hyderabad", "HYDERABAD" -> "Hyderabad")
 * Only capitalizes if the location is a valid Indian city
 * @param location - Location string to capitalize
 * @returns Properly capitalized location if valid Indian city, empty string otherwise
 */
export const capitalizeIndianCity = (location: string): string => {
  if (!location || typeof location !== 'string') return '';

  const normalized = location.trim().toLowerCase();
  const matchedCity = INDIAN_CITIES.find(city => city.toLowerCase() === normalized);

  return matchedCity || '';
};
